import { Container } from 'inversify';
import { AppController } from '../controllers/app-controller';
import { AuthController } from '../controllers/auth-controller';
import { BlogsController } from '../controllers/blogs-controller';
import { CommentsController } from '../controllers/comments-controller';
import { DevicesController } from '../controllers/devices-controller';
import { PostsController } from '../controllers/posts-controller';
import { UsersController } from '../controllers/users-controller';
import { VideosController } from '../controllers/videos-controller';
import { AuthService } from '../domain/auth-service';
import { BlogsService } from '../domain/blogs-service';
import { CommentsService } from '../domain/comments-service';
import { DevicesService } from '../domain/devices-service';
import { PostsService } from '../domain/posts-service';
import { RequestsService } from '../domain/requests-service';
import { UsersService } from '../domain/users-service';
import { VideosService } from '../domain/videos-service';
import { BlogsRepository } from '../repositories/blogs-repository';
import { CommentsRepository } from '../repositories/comments-repository';
import { DevicesRepository } from '../repositories/devices-repository';
import { PostsRepository } from '../repositories/posts-repository';
import { RequestsRepository } from '../repositories/requests-repository';
import { UsersRepository } from '../repositories/users-repository';
import { VideosRepository } from '../repositories/videos-repository';

export const container = new Container();

container.bind(AppController).to(AppController);
container.bind(AuthController).to(AuthController);
container.bind(BlogsController).to(BlogsController);
container.bind(CommentsController).to(CommentsController);
container.bind(DevicesController).to(DevicesController);
container.bind(PostsController).to(PostsController);
container.bind(UsersController).to(UsersController);
container.bind(VideosController).to(VideosController);
container.bind(AuthService).to(AuthService);
container.bind(BlogsService).to(BlogsService);
container.bind(CommentsService).to(CommentsService);
container.bind(DevicesService).to(DevicesService);
container.bind(PostsService).to(PostsService);
container.bind(RequestsService).to(RequestsService);
container.bind(UsersService).to(UsersService);
container.bind(VideosService).to(VideosService);
container.bind(BlogsRepository).to(BlogsRepository);
container.bind(CommentsRepository).to(CommentsRepository);
container.bind(DevicesRepository).to(DevicesRepository);
container.bind(PostsRepository).to(PostsRepository);
container.bind(RequestsRepository).to(RequestsRepository);
container.bind(UsersRepository).to(UsersRepository);
container.bind(VideosRepository).to(VideosRepository);
